version: '3.9'

services:
  laravel-app:
    build:
      context: ./dockerfile
    container_name: laravel-web-ptn
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./web:/var/www
    networks:
      - laravel

  laravel-webserver:
    image: nginx:alpine
    container_name: laravel-webserver-ptn
    restart: unless-stopped
    ports:
      - "8089:80"
    volumes:
      - ./web:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      - laravel

networks:
  laravel:
    external: true
